from google_adk import Agent
from google_adk.config import AgentConfig
from google_adk.models import Gemini25Flash
from skills.agent_skills import reporting_skill

config = AgentConfig(
    name="report_agent",
    model=Gemini25Flash(),
    system_instruction="You are a specialized summarizing agent. You do not call data tools directly. Your sole job is to accept completed text summaries generated by specialized analytical engines and format them into a beautiful, professional Markdown document containing an Executive Summary, Critical Risks, and a numbered 30-day Action Plan."
)

report_agent = Agent(
    config=config,
    skills=[reporting_skill]
)
